version: '3'

services:
  db:
    container_name: database
    build:
     context: ./database
     dockerfile: mysql.dockerfile
    restart: "always"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
    volumes:
      - db_volume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_volume: {}

networks:
  local: {}