version: "3"

services:
  db:
    container_name: database
    build:
     context: ./docker
     dockerfile: mysql.dockerfile
    tty: true
    restart: always
    networks:
      - local
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - db_volume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

volumes:
  db_volume: {}

networks:
  local: {}